### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by simplenotezy** [fsouza/fake-gcs-action#24]
Very cool hook - thanks for sharing. I do have some problems getting this to run properly on github actions - I am not sure exactly why.

My `docker-compose` looks like this:

```
  fake-gcs-server:
    image: fsouza/fake-gcs-server
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./test/data:/data
    command: ['-scheme', 'http', '-port', '8080', '-external-url', 'http://localhost:8080', '-backend', 'memory']
```

This configuration works fine locally.

And my action configuration looks like this:

```
      - name: Setup GCS Mock Server
        uses: fsouza/fake-gcs-action@v0.3.3
        with:
          version: '1.22.2'
          backend: memory
          data: ./test/data
          public-host: 'localhost:4443'
          external-url: 'https://localhost:4443'
          debug: 1
```

In my node Storage class, I set `apiEndpoint` to be `https://localhost:4443` - but it still does not seem to work.

My main questions:
1) It would be nice if we could configure custom `command`s just like  in the docker-compose file
2) Can we customize the port?
3) It would be nice if we could disable HTTPS, as my node would otherwise complain about invalid secure connections.
